---
- hosts: linux
  become: yes
  tasks:
  - name: Create a file.
    command: echo "malicious_code_example" > /etc/malicious.conf
      creates: /etc/malicious.conf
  - name: Modify file.
    command: echo "modification_to_example" >> /etc/malicious.conf | /tmp/modify_proof.log
      creates: /tmp/modify_proof.log
  - name: Delete file.
    command: rm -f /etc/malicious.conf
  - command: rm -f /tmp/modify_proof.log
